#!/usr/bin/env bash
# Install nginx and configure
sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx restart

