#!/usr/bin/env bash
# Install nginx and configure
sudo apt -y update 
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
service nginx start

