#!/usr/bin/env bash
# Install nginx and configure
my_config="Location {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n"
sudo sed -i "301 $my_config" /etc/nginx/sites-available/default
service nginx start

