#!/usr/bin/env bash
# Install nginx and configure
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
myconfig="rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/listen 80 default_server;/$myconfig/" /etc/nginx/sites-enabled/default
service nginx start

