#!/usr/bin/env bash
# Install nginx and configure
sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Ceci n'est pas une page' > /var/www/html/404.html
sudo sed -i '/listen 80 default_server;/a \\trewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
service nginx start
