#!/usr/bin/env bash
# Install nginx and configure
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
my_config="\\\tadd_header X-Served-By "$HOSTNAME";"
sudo sed -i "28i $my_config" /etc/nginx/nginx.conf
sudo service nginx restart
