#!/usr/bin/env bash
# Installing and configuring haproxy to load balance between web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*
sudo service haproxy start
echo -e "\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_backend\n\nbackend http_backend\n\tbalance roundrobin\n\tserver 1043-web-01 35.229.103.77:80 check\n\tserver 1043-web-02 54.234.224.67:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
