#!/usr/bin/env bash
# fizz buzz
for k in {1..100}
do
if ((k % 3 == 0 && k % 5 == 0 ));
then
echo FizzBuzz
elif ((k % 5 == 0 ));
then
echo Buzz
elif ((k % 3 == 0 ));
then
echo Fizz
else
echo $k
fi
done