#!/usr/bin/env bash
# display numbers 1-20
k=0
while [ $k != 20 ];
do
k=$((k + 1))
echo $k
case $k in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
done