#!/usr/bin/env bash
# Clock that displays the time for 12 hours and 59 minutes
min=1
h=0
while [ $h != 13 ];
do
echo "Hour: $h"
while [ $min != 60 ];
do
echo $min
min=$((min + 1))
done
min=1
h=$((h + 1))
done