#!/usr/bin/env bash
# running nginx as nginx user
echo "user nginx;" >> /etc/nginx/nginx.conf
sudo pkill -f apache2
sudo chmod +rw /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
su -c "service nginx restart" nginx
